name: Checkstyle

on:
  push:

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Run Checkstyle
      run: |
        wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.0/checkstyle-10.0-all.jar
        java -jar checkstyle-10.18.2-all.jar -c ./checkstyle.xml src/main
